services:
  mongodb:
    image: mongo:7
    container_name: pentesting-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: pentesting
    volumes:
      - mongodb_data:/data/db
      - ./backend/seeders:/docker-entrypoint-initdb.d:ro
    ports:
      - "27017:27017"
    networks:
      - pentesting-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  app:
    build: .
    container_name: pentesting-app
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/pentesting
      - PORT=9000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - pentesting-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  pentesting-network:
    driver: bridge
